#!/usr/bin/env node

/**
 * sync-adblock.mjs — copies /adblock assets into the iOS Noirva app bundle.
 *
 * Usage: node scripts/sync-adblock.mjs
 *
 * The copies under Noirva/Noirva/Resources/ are generated by this script.
 * Edit the originals in /adblock/, not the copies.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..', '..')
const adblockDir = resolve(root, 'adblock')
const iosResourcesDir = resolve(root, 'ios', 'Noirva', 'Noirva', 'Resources')

// Ensure the Resources directory exists.
if (!existsSync(iosResourcesDir)) {
  mkdirSync(iosResourcesDir, { recursive: true })
}

// Copy hosts.json
const hostsSrc = resolve(adblockDir, 'hosts.json')
const hostsDst = resolve(iosResourcesDir, 'hosts.json')
writeFileSync(hostsDst, readFileSync(hostsSrc, 'utf8'))
console.log(`Copied hosts.json -> ${hostsDst}`)

// Copy inject.js
const injectSrc = resolve(adblockDir, 'inject.js')
const injectDst = resolve(iosResourcesDir, 'inject.js')
writeFileSync(injectDst, readFileSync(injectSrc, 'utf8'))
console.log(`Copied inject.js -> ${injectDst}`)

console.log('iOS ad-block assets synced.')
