export interface StreamItem {
  url: string
  type?: string
  title: string
  thumbnail: string
  uploaderName: string
  uploaderUrl?: string
  uploaderAvatar?: string
  uploadedDate?: string
  duration: number
  views: number
  uploaderVerified?: boolean
}

export interface PipedStream {
  url: string
  quality: string
  mimeType: string
  videoOnly: boolean
  height?: number
  width?: number
  fps?: number
  bitrate?: number
}

export interface Subtitle {
  url: string
  code: string
  name: string
  autoGenerated?: boolean
}

export interface VideoStreamsResponse {
  title: string
  description: string
  uploadDate: string
  uploader: string
  uploaderUrl: string
  uploaderAvatar?: string
  thumbnailUrl: string
  hls: string | null
  dash?: string | null
  duration: number
  views: number
  likes: number
  livestream?: boolean
  audioStreams: PipedStream[]
  videoStreams: PipedStream[]
  relatedStreams: StreamItem[]
  subtitles: Subtitle[]
  _source?: string
}

export interface Comment {
  author: string
  commentId: string
  commentText: string
  commentedTime: string
  thumbnail: string
  likeCount: number
  pinned?: boolean
  verified?: boolean
}

export interface CommentsResponse {
  comments: Comment[]
  disabled: boolean
  nextpage: string | null
}

export interface ChannelResponse {
  id: string
  name: string
  avatarUrl: string
  bannerUrl?: string
  description: string
  subscriberCount: number
  verified?: boolean
  nextpage: string | null
  relatedStreams: StreamItem[]
}

export interface SearchResponse {
  items: StreamItem[]
  nextpage: string | null
}
